var searchData=
[
  ['c_20foundations_20–_20course_0',['C++ Foundations – Course',['../group__cpp__course.html',1,'']]],
  ['calificadores_1',['Lesson 01 – Tipos de datos, scope y calificadores',['../group__cpp__lesson__01.html',1,'']]],
  ['checklist_20final_2',['Checklist final',['../group__cpp__lesson__00.html#lesson00_checklist',1,'']]],
  ['ci_20coverage_20report_3',['CI coverage report',['../md_README.html#autotoc_md24',1,'']]],
  ['clamp_4',['Clamp',['../namespaceMathUtils.html#a7529e532eae0704dae2f68b037ae1a66',1,'MathUtils']]],
  ['clonar_20y_20preparar_20el_20repositorio_5',['Clonar y preparar el repositorio',['../group__cpp__lesson__00.html#lesson00_repo',1,'']]],
  ['cmake_6',['Flujo de compilación local con CMake',['../group__cpp__lesson__00.html#lesson00_build',1,'']]],
  ['cmake_20no_20encuentra_20compilador_7',['CMake no encuentra compilador',['../group__cpp__lesson__00.html#lesson00_troubleshooting_cmake',1,'']]],
  ['cmake_20se_20queda_20atorado_20con_20config_20vieja_8',['CMake se queda &quot;atorado&quot; con config vieja',['../group__cpp__lesson__00.html#lesson00_troubleshooting_cache',1,'']]],
  ['compilación_20local_20con_20cmake_9',['Flujo de compilación local con CMake',['../group__cpp__lesson__00.html#lesson00_build',1,'']]],
  ['compilado_10',['Asegurar que el proyecto está compilado',['../group__cpp__lesson__00.html#lesson00_tests_build',1,'']]],
  ['compilador_11',['CMake no encuentra compilador',['../group__cpp__lesson__00.html#lesson00_troubleshooting_cmake',1,'']]],
  ['comunes_20y_20soluciones_20rápidas_12',['Errores comunes y soluciones rápidas',['../group__cpp__lesson__00.html#lesson00_troubleshooting',1,'']]],
  ['con_20cmake_13',['Flujo de compilación local con CMake',['../group__cpp__lesson__00.html#lesson00_build',1,'']]],
  ['con_20config_20vieja_14',['CMake se queda &quot;atorado&quot; con config vieja',['../group__cpp__lesson__00.html#lesson00_troubleshooting_cache',1,'']]],
  ['con_20ctest_15',['Ejecutar pruebas con CTest',['../group__cpp__lesson__00.html#lesson00_tests_ctest',1,'']]],
  ['config_20vieja_16',['CMake se queda &quot;atorado&quot; con config vieja',['../group__cpp__lesson__00.html#lesson00_troubleshooting_cache',1,'']]],
  ['configuración_20debug_20y_20release_17',['Configuración Debug y Release',['../group__cpp__lesson__00.html#lesson00_build_debug_release',1,'']]],
  ['configuración_20del_20entorno_20de_20trabajo_20local_18',['Lesson 00 – Configuración del entorno de trabajo (local)',['../group__cpp__lesson__00.html',1,'']]],
  ['course_19',['C++ Foundations – Course',['../group__cpp__course.html',1,'']]],
  ['course_2edox_20',['Course.dox',['../Course_8dox.html',1,'']]],
  ['coverage_20report_21',['CI coverage report',['../md_README.html#autotoc_md24',1,'']]],
  ['cpp_20foundations_22',['cpp foundations',['../index.html',1,'Cpp Foundations'],['../md_README.html',1,'cpp-foundations']]],
  ['ctest_23',['Ejecutar pruebas con CTest',['../group__cpp__lesson__00.html#lesson00_tests_ctest',1,'']]],
  ['cuando_20sea_20necesario_24',['Limpiar build (cuando sea necesario)',['../group__cpp__lesson__00.html#lesson00_build_clean',1,'']]]
];
