var searchData=
[
  ['cómo_20usar_20este_20repositorio_0',['Cómo usar este repositorio',['../index.html#mainpage_how_to_use',1,'']]],
  ['c_20foundations_1',['C++ Foundations',['../index.html',1,'']]],
  ['c_20foundations_20–_20course_2',['C++ Foundations – Course',['../group__cpp__course.html',1,'']]],
  ['calificadores_3',['calificadores',['../group__cpp__lesson__01.html',1,'Lesson 01 – Tipos de datos, scope y calificadores'],['../index.html#mainpage_lesson01',1,'Lesson 01 – Tipos de datos, scope y calificadores']]],
  ['checklist_20final_4',['Checklist final',['../group__cpp__lesson__00.html#lesson00_checklist',1,'']]],
  ['ci_20coverage_20report_5',['CI coverage report',['../md_README.html#autotoc_md29',1,'']]],
  ['clamp_6',['Clamp',['../namespaceMathUtils.html#a7529e532eae0704dae2f68b037ae1a66',1,'MathUtils']]],
  ['clonar_20y_20preparar_20el_20repositorio_7',['Clonar y preparar el repositorio',['../group__cpp__lesson__00.html#lesson00_repo',1,'']]],
  ['cmake_8',['Flujo de compilación local con CMake',['../group__cpp__lesson__00.html#lesson00_build',1,'']]],
  ['commit_20inicial_9',['Pasos del commit inicial',['../group__cpp__lesson__00.html#lesson00_git_initial_commit',1,'']]],
  ['commit_20inicial_20obligatorio_10',['Commit inicial obligatorio',['../group__cpp__lesson__00.html#lesson00_git_workflow',1,'']]],
  ['compilación_20local_20con_20cmake_11',['Flujo de compilación local con CMake',['../group__cpp__lesson__00.html#lesson00_build',1,'']]],
  ['compilación_20y_20pruebas_20locales_12',['Compilación y pruebas locales',['../index.html#mainpage_local_build',1,'']]],
  ['con_20cmake_13',['Flujo de compilación local con CMake',['../group__cpp__lesson__00.html#lesson00_build',1,'']]],
  ['configuración_20del_20entorno_20de_20trabajo_14',['Lesson 00 – Configuración del entorno de trabajo',['../index.html#mainpage_lesson00',1,'']]],
  ['configuración_20del_20entorno_20de_20trabajo_20local_15',['Lesson 00 – Configuración del entorno de trabajo (local)',['../group__cpp__lesson__00.html',1,'']]],
  ['course_16',['C++ Foundations – Course',['../group__cpp__course.html',1,'']]],
  ['course_2edox_17',['Course.dox',['../Course_8dox.html',1,'']]],
  ['course_5fguard_5fenabled_18',['Protección del curso (COURSE_GUARD_ENABLED)',['../group__cpp__lesson__00.html#lesson00_course_guard',1,'']]],
  ['coverage_20report_19',['CI coverage report',['../md_README.html#autotoc_md29',1,'']]],
  ['cpp_20foundations_20',['cpp-foundations',['../md_README.html',1,'']]],
  ['curso_21',['curso',['../index.html#mainpage_course',1,'Estructura del curso'],['../index.html#mainpage_expectations',1,'Expectativas del curso']]],
  ['curso_20course_5fguard_5fenabled_22',['Protección del curso (COURSE_GUARD_ENABLED)',['../group__cpp__lesson__00.html#lesson00_course_guard',1,'']]]
];
