var searchData=
[
  ['datos_20scope_20y_20calificadores_0',['datos scope y calificadores',['../group__cpp__lesson__01.html',1,'Lesson 01 – Tipos de datos, scope y calificadores'],['../index.html#mainpage_lesson01',1,'Lesson 01 – Tipos de datos, scope y calificadores']]],
  ['de_20compilación_1',['Archivos de compilación',['../group__cpp__lesson__00.html#lesson00_gitignore_build',1,'']]],
  ['de_20corrección_20estándar_2',['Secuencia de corrección estándar',['../group__cpp__lesson__00.html#lesson00_git_fix_steps',1,'']]],
  ['de_20datos_20scope_20y_20calificadores_3',['de datos scope y calificadores',['../group__cpp__lesson__01.html',1,'Lesson 01 – Tipos de datos, scope y calificadores'],['../index.html#mainpage_lesson01',1,'Lesson 01 – Tipos de datos, scope y calificadores']]],
  ['de_20herramientas_4',['Instalación de herramientas',['../group__cpp__lesson__00.html#lesson00_install',1,'']]],
  ['de_20la_20documentación_5',['Navegación de la documentación',['../index.html#mainpage_navigation',1,'']]],
  ['de_20oro_6',['Regla de oro',['../group__cpp__lesson__00.html#lesson00_git_fix_rule',1,'']]],
  ['de_20pruebas_20locales_7',['Ejecución de pruebas locales',['../group__cpp__lesson__00.html#lesson00_tests',1,'']]],
  ['de_20trabajo_8',['Lesson 00 – Configuración del entorno de trabajo',['../index.html#mainpage_lesson00',1,'']]],
  ['de_20trabajo_20esperado_9',['Flujo de trabajo esperado',['../index.html#mainpage_workflow',1,'']]],
  ['de_20trabajo_20y_20flujo_20fork_20upstream_10',['Lesson 00 – Configuración del entorno de trabajo y flujo Fork + Upstream',['../group__cpp__lesson__00.html',1,'']]],
  ['de_20tt_20gitignore_20tt_11',['Ejemplo mínimo de &lt;tt&gt;.gitignore&lt;/tt&gt;',['../group__cpp__lesson__00.html#lesson00_gitignore_example',1,'']]],
  ['de_20un_20merge_12',['Arreglar un CI fallido después de un merge',['../group__cpp__lesson__00.html#lesson00_git_fix',1,'']]],
  ['debian_13',['Linux (Ubuntu/Debian)',['../group__cpp__lesson__00.html#lesson00_install_linux',1,'']]],
  ['del_20commit_20inicial_14',['Pasos del commit inicial',['../group__cpp__lesson__00.html#lesson00_git_commit_steps',1,'']]],
  ['del_20curso_15',['del curso',['../index.html#mainpage_course',1,'Estructura del curso'],['../index.html#mainpage_expectations',1,'Expectativas del curso']]],
  ['del_20curso_3a_20fork_20upstream_16',['Modelo del curso: Fork + Upstream',['../group__cpp__lesson__00.html#lesson00_repo_model',1,'']]],
  ['del_20entorno_17',['Verificación del entorno',['../group__cpp__lesson__00.html#lesson00_verify',1,'']]],
  ['del_20entorno_20de_20trabajo_18',['Lesson 00 – Configuración del entorno de trabajo',['../index.html#mainpage_lesson00',1,'']]],
  ['del_20entorno_20de_20trabajo_20y_20flujo_20fork_20upstream_19',['Lesson 00 – Configuración del entorno de trabajo y flujo Fork + Upstream',['../group__cpp__lesson__00.html',1,'']]],
  ['del_20repositorio_20',['del repositorio',['../group__cpp__lesson__00.html#lesson00_structure',1,'Estructura del repositorio'],['../index.html#mainpage_repo_structure',1,'Estructura del repositorio']]],
  ['desde_20github_20sync_20fork_21',['Actualizar desde GitHub (Sync fork)',['../group__cpp__lesson__00.html#lesson00_repo_sync_github',1,'']]],
  ['desde_20la_20terminal_22',['Actualizar desde la terminal',['../group__cpp__lesson__00.html#lesson00_repo_sync_terminal',1,'']]],
  ['después_20de_20un_20merge_23',['Arreglar un CI fallido después de un merge',['../group__cpp__lesson__00.html#lesson00_git_fix',1,'']]],
  ['documentación_24',['Navegación de la documentación',['../index.html#mainpage_navigation',1,'']]]
];
